

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    depends_on:
      - db

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:80"
    depends_on:
      - auth-service

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: openECG
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./FRONTEND
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - dist:/app/dist

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - dist:/usr/share/nginx/html
    depends_on:
      - frontend

  image-upload:
    build:
      context: ./image-upload
    container_name: image-upload-service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=openECG
    depends_on:
      - db


volumes:
  dist:
  db_data:
