

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    depends_on:
      - db

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:80"
    depends_on:
      - auth-service

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: openECG
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./FRONTEND
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - dist:/app/dist

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - dist:/usr/share/nginx/html
    depends_on:
      - frontend

  image-upload:
    build:
      context: ./image-upload
    container_name: image-upload-service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=openECG
    depends_on:
      - db
    volumes:
      - ./image-upload/uploads:/app/uploads
    
  gpt-service:
    build:
      context: ./gpt-service
    container_name: gpt-service
    environment:
      DATABASE_URI: mysql://user:userpassword@db:3306/openECG  # Conexão com o banco de dados MySQL
      GPT_API_URL: https://sua-url-gpt-personalizada.com/endpoint  # Substitua pela URL real do serviço GPT
      GPT_API_KEY: sk-sua-chave-de-api-personalizada  # Chave de API real do GPT
    depends_on:
      - db
    ports:
      - "5003:5003"
    volumes:
      - ./image-upload/uploads:/app/uploads  # Compartilhamento do diretório de uploads com o serviço de upload
    
volumes:
  dist:
  db_data:
